<a href="https://colab.research.google.com/github/shevank/deep-learning/blob/main/RNC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive') #  force_remount=True 
import pandas as pd

Mounted at /content/drive


In [8]:
# Imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import mnist
from sklearn.model_selection import train_test_split

In [48]:
filename = '/content/drive/MyDrive/Data Science 2022/fashion-mnist_train.csv' # Excel O CSV

df = pd.read_csv(filename) #csv 

df.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0        30        43         0   
3       0  ...         3         0         0         0         0         1   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [ ]:
filename = '/content/drive/MyDrive/Data Science 2022/fashion-mnist_test.csv' # Excel O CSV

df2 = pd.read_csv(filename) #csv 

df2.head() 

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      0       0       0       0       0       0       0       0       9   
1      1       0       0       0       0       0       0       0       0   
2      2       0       0       0       0       0       0      14      53   
3      2       0       0       0       0       0       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel775  pixel776  pixel777  pixel778  pixel779  pixel780  \
0       8  ...       103        87        56         0         0         0   
1       0  ...        34         0         0         0         0         0   
2      99  ...         0         0         0         0        63        53   
3       0  ...       137       126       140         0       133       224   
4       0  ...         0         0         0         0         0         0   

   pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0  
1         0         0         0         0  
2        31         0         0         0  
3       222        56         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [49]:
X = df.drop(columns=['label']).values/255
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [50]:
y = df['label'].values
y

array([2, 9, 6, ..., 8, 8, 7])

In [51]:
#Hago el split de datos 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
# Reformar datos
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)

In [53]:
X_train.shape

(48000, 28, 28, 1)

In [54]:
# Paso 1: Definir nuestra estructura de red
# Guardar la forma de entrada
input_shape = X_train.shape[1:4]
input_shape

(28, 28, 1)

In [55]:
#Defino las clases 
y_train = to_categorical(y_train, num_classes = 10)
y_test = to_categorical(y_test, num_classes = 10)

In [56]:
# Modelo secuencial
model = Sequential()

In [57]:
# Capa convolucional
model.add(Conv2D(filters = 8, # Cuantos filtros quieres usar
                 kernel_size = 3, # tamaño de cada filtro
                 input_shape = input_shape)) # ¿Cuál es la forma de tus características de entrada (definimos esto arriba)
# Pooling layer
model.add(MaxPooling2D(pool_size = 2)) # Tamaño de pooling
# Capa de aplanamiento
model.add(Flatten())
# Capa de salida
model.add(Dense(10, # Cuantas posibilidades de salida tenemos
                activation = 'softmax')) # ¿Qué función de activación estás usando?

In [58]:
# Paso 2: compilar
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['acc'])

In [59]:
# Paso 3: ajustar nuestro modelo
history = model.fit(X_train, y_train,
                    validation_data = (X_test, y_test), 
                    epochs=20)

Epoch 1/20
1500/1500 [==============================] - 17s 11ms/step - loss: 0.5406 - acc: 0.8144 - val_loss: 0.4265 - val_acc: 0.8515
Epoch 2/20
1500/1500 [==============================] - 17s 11ms/step - loss: 0.4125 - acc: 0.8570 - val_loss: 0.3977 - val_acc: 0.8593
Epoch 3/20
1500/1500 [==============================] - 17s 11ms/step - loss: 0.3790 - acc: 0.8681 - val_loss: 0.3711 - val_acc: 0.8702
Epoch 4/20
1500/1500 [==============================] - 17s 11ms/step - loss: 0.3559 - acc: 0.8770 - val_loss: 0.3807 - val_acc: 0.8640
Epoch 5/20
1500/1500 [==============================] - 17s 11ms/step - loss: 0.3387 - acc: 0.8811 - val_loss: 0.3460 - val_acc: 0.8788
Epoch 6/20
1500/1500 [==============================] - 17s 11ms/step - loss: 0.3251 - acc: 0.8871 - val_loss: 0.3429 - val_acc: 0.8818
Epoch 7/20
1500/1500 [==============================] - 18s 12ms/step - loss: 0.3145 - acc: 0.8897 - val_loss: 0.3344 - val_acc: 0.8838
Epoch 8/20
1500/1500 [==========================

In [60]:
X2 = df2.drop(columns=['label']).values/255
X2

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.00392157,
        0.        ],
       [0.        , 0.00392157, 0.01176471, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [61]:
y2 = df2['label'].values

In [62]:
# Reformar datos
X2 = X2.reshape(X2.shape[0], 28, 28, 1)
X2

array([[[[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.01568627],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.00392157],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        ...,

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]],

        [[0.        ],
         [0.        ],
         [0.        ],
         ...,
         [0.        ],
         [0.        ],
         [0.        ]]],


       [[[0.        ],
         [0.        ],
         [0.  

In [63]:
X2.shape

(10000, 28, 28, 1)

In [66]:
class_names = ["Polera/top", "Pantalón", "Suéter", "Vestido", "Abrigo",
               "Sandalia", "Camisa", "Zapatilla", "Bolso", "Botín"] # 10 clases

In [77]:
for dato in range (1,100,1):

  prediction = model.predict(X2)
  classes_x=np.argmax(prediction,axis=1)
  print("Predicción:", class_names[classes_x[dato]])
  print("Clase Real:", class_names[y2[dato]])

Predicción: Pantalón
Clase Real: Pantalón
Predicción: Camisa
Clase Real: Suéter
Predicción: Suéter
Clase Real: Suéter
Predicción: Vestido
Clase Real: Vestido
Predicción: Suéter
Clase Real: Suéter
Predicción: Bolso
Clase Real: Bolso
Predicción: Camisa
Clase Real: Camisa
Predicción: Sandalia
Clase Real: Sandalia
Predicción: Polera/top
Clase Real: Polera/top
Predicción: Vestido
Clase Real: Vestido
Predicción: Suéter
Clase Real: Abrigo
Predicción: Abrigo
Clase Real: Abrigo
Predicción: Camisa
Clase Real: Camisa
Predicción: Bolso
Clase Real: Bolso
Predicción: Sandalia
Clase Real: Sandalia
Predicción: Abrigo
Clase Real: Camisa
Predicción: Vestido
Clase Real: Vestido
Predicción: Camisa
Clase Real: Camisa
Predicción: Abrigo
Clase Real: Abrigo
Predicción: Abrigo
Clase Real: Abrigo
Predicción: Abrigo
Clase Real: Abrigo
Predicción: Suéter
Clase Real: Suéter
Predicción: Pantalón
Clase Real: Pantalón
Predicción: Sandalia
Clase Real: Sandalia
Predicción: Zapatilla
Clase Real: Zapatilla
Predicción: Bo